-- Social platform schema — matches the relational schema (lab 2)
-- Import via phpMyAdmin, or: mysql -u root -p < schema.sql

CREATE DATABASE IF NOT EXISTS social_app_db;
USE social_app_db;

CREATE TABLE USER (
  Email           VARCHAR(255) PRIMARY KEY,
  HashedPassword  VARCHAR(255) NOT NULL,
  FirstName       VARCHAR(100) NOT NULL,
  LastName        VARCHAR(100) NOT NULL,
  BirthDate       DATE NOT NULL
);

CREATE TABLE FRIENDS_WITH (
  RequesterEmail  VARCHAR(255) NOT NULL,
  ReceiverEmail   VARCHAR(255) NOT NULL,
  Status          ENUM('pending','accepted') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (RequesterEmail, ReceiverEmail),
  FOREIGN KEY (RequesterEmail) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ReceiverEmail)  REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TEXT_POSTS (
  PostID          INT AUTO_INCREMENT PRIMARY KEY,
  UserEmail       VARCHAR(255) NOT NULL,
  Post_Content    TEXT NOT NULL,
  P_UploadTime    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserEmail) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMMENT (
  CommentID        INT AUTO_INCREMENT PRIMARY KEY,
  UserEmail        VARCHAR(255) NOT NULL,
  PostID           INT NOT NULL,
  ParentCommentID  INT NULL,
  Comment_content  TEXT NOT NULL,
  C_UploadTime     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserEmail) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (PostID) REFERENCES TEXT_POSTS(PostID) ON DELETE CASCADE,
  FOREIGN KEY (ParentCommentID) REFERENCES COMMENT(CommentID) ON DELETE CASCADE
);

CREATE TABLE POST_LIKES (
  UserEmail  VARCHAR(255) NOT NULL,
  PostID     INT NOT NULL,
  PRIMARY KEY (UserEmail, PostID),
  FOREIGN KEY (UserEmail) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (PostID) REFERENCES TEXT_POSTS(PostID) ON DELETE CASCADE
);

CREATE TABLE COMMENT_LIKES (
  UserEmail  VARCHAR(255) NOT NULL,
  CommentID  INT NOT NULL,
  PRIMARY KEY (UserEmail, CommentID),
  FOREIGN KEY (UserEmail) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CommentID) REFERENCES COMMENT(CommentID) ON DELETE CASCADE
);

CREATE TABLE CHATROOM (
  ChatRoomID  INT AUTO_INCREMENT PRIMARY KEY,
  UserEmail1  VARCHAR(255) NOT NULL,
  UserEmail2  VARCHAR(255) NOT NULL,
  FOREIGN KEY (UserEmail1) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (UserEmail2) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_chatroom_pair (UserEmail1, UserEmail2)
);

CREATE TABLE MESSAGE (
  MessageID        INT AUTO_INCREMENT PRIMARY KEY,
  UserEmail        VARCHAR(255) NOT NULL,
  ChatRoomID       INT NOT NULL,
  Message_Content  TEXT NOT NULL,
  Time_Sent        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserEmail) REFERENCES USER(Email) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ChatRoomID) REFERENCES CHATROOM(ChatRoomID) ON DELETE CASCADE
);
